### ISSUE TITLE
Native method not found: com.unity3d.player.UnityPlayer.UnitySendMessage

### ISSUE THREAD

**Issue by otsuga** [kobakei/unity-gcm#1]
First thanks for this asset!

When i receive a message when the application is closed im getting this error on logcat.

 E/AndroidRuntime(3480): Caused by: java.lang.UnsatisfiedLinkError: Native method not found: com.unity3d.player.UnityPlayer.UnitySendMessage:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)
08-08 16:20:45.005: E/AndroidRuntime(3480):     at com.kskkbys.unitygcmplugin.Util.sendMessage(Util.java:22)
08-08 16:20:45.005: E/AndroidRuntime(3480):     at com.kskkbys.unitygcmplugin.Util.sendMessage(Util.java:22)
08-08 16:20:45.005: E/AndroidRuntime(3480):     at com.kskkbys.unitygcmplugin.UnityGCMIntentService.onMessage(UnityGCMIntentService.java:50)

**Comment by cancerballs** [comment]
I also get an error like this. No idea what causes it. I posted the logcat to SO.

I receive the notification to the device but the app does not start.

http://stackoverflow.com/questions/28052802/gcm-notification-received-on-device-does-not-start-the-application

**Comment by LeshM** [comment]
I found out that the gcm plugin is setting a specific unity activity as the pending intent of the notification.
As soon as I added the activity to my AndroidManifest.xml it worked!

**Comment by cancerballs** [comment]
@LeshM: How did you find out about the specific unity activity?

**Comment by LeshM** [comment]
I dug into the java code :)

   Omer Leshem @ Round Robin LTD.

  +972-50-869-1763 | RndRobin.com <http://rndrobin.com/>

**Comment by cancerballs** [comment]
The only relevant activity I can find is 

private static final String SERVICE_NAME = "com.kskkbys.unitygcmplugin.UnityGCMIntentService";

in UnityGCMBroadcastReceiver.java.

I have that in my AndroidManifest.xml as

<service android:name="com.kskkbys.unitygcmplugin.UnityGCMIntentService" />

**Comment by LeshM** [comment]
Here:
// Intent 
		Intent intent = new Intent(context, UnityPlayerProxyActivity.class);
		PendingIntent contentIntent = PendingIntent.getActivity(context, REQUEST_CODE_UNITY_ACTIVITY, intent, PendingIntent.FLAG_UPDATE_CURRENT);
		

https://github.com/kobakei/unity-gcm/blob/master/source/UnityGcmPlugin/src/com/kskkbys/unitygcmplugin/UnityGCMNotificationManager.java

**Comment by cancerballs** [comment]
@LeshM I defined the missing activities based on the ones you posted here. Now the app starts when I tap the notification. Your help was invaluable. Thank you.

I noticed that the errors in logcat are still present. This issue didn't seem to have anything to do with the erros.

**Comment by LeshM** [comment]
Glad I could help ^_^

**Comment by Cherubyx** [comment]
Thanks @LeshM, this helps alot. However I already have a MAIN activity that is not android:name="com.unity3d.player.UnityPlayerProxyActivity" how can I replace that with my current MAIN one? I realized it is imported to the java code. I'm not sure if I can just replace it without rebuilding the .jar file.

**Comment by Skatola** [comment]
Excuse me... Cancerballs what did u exactly?
I have the same problem, notification does not start the app... but i don't understand what i have to do for let it work : (
Seems like LeshM give you a java string and solved this problem...where i have to copy that? 
Sorry i'm a novice unity developer and really need your help : )

**Comment by cancerballs** [comment]
@Skatola 
See LeshM's comment for activities to be defined in the android manifesto.

**Comment by Skatola** [comment]
@cancerballs 
Thank you for your reply : )
I have no experience in java and i have trouble to edit the manifest myself, u find the missing activities tnx to LeshM's post, but what exactly have u added in your manifest?
I simply don't understand what that string means, i barely know c# for unity basic scripting : )
Really appreciate your help, thank you

**Comment by Skatola** [comment]
ok new problem : D
with the new activities the app start when the notification is tapped, but if the app is already started or it's in background it crash and start again...any solution? :\

**Comment by pgilmorepf** [comment]
Sorry, this is somewhat unrelated, but this is the only place I've found this:
REQUEST_CODE_UNITY_ACTIVITY = 1001;
and
PendingIntent.getActivity(intent, REQUEST_CODE_UNITY_ACTIVITY, ...

Why?  What's magical about 1001?  That value doesn't show up anywhere else (Like the Unity Documentation), and I can't find any other explanation about why that works, it just does.
