### ISSUE TITLE
hey! about push not in the app...

### ISSUE THREAD

**Issue by Rafaelkas** [kobakei/unity-gcm#15]
i got this erorr:

D/dalvikvm( 9994): threadid=10
(IntentService[GCMIntentService-DynamicSenderIds-1]): calling run()
V/UnityGCMIntentService( 9994): onMessage
V/UnityGCMIntentService( 9994): badge: 7
V/UnityGCMIntentService( 9994): collapse_key: do_not_collapse
V/UnityGCMIntentService( 9994): from: 149262229651
V/UnityGCMIntentService( 9994): alert: gvgvgv
D/dalvikvm( 9994): Trying to load lib
/data/app-lib/com.slotoparty.slotoparty-1/libmain.so 0x41ba9978
D/dalvikvm( 9994): Added shared lib
/data/app-lib/com.slotoparty.slotoparty-1/libmain.so 0x41ba9978
W/dalvikvm( 9994): No implementation found for native
Lcom/unity3d/player/UnityPlayer;.UnitySendMessage:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
W/System.err( 9994): java.lang.UnsatisfiedLinkError: Native method not
found: com.unity3d.player.UnityPlayer.UnitySendMessage:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
W/System.err( 9994): at
com.unity3d.player.UnityPlayer.UnitySendMessage(Native Method)
W/System.err( 9994): at
com.kskkbys.unitygcmplugin.Util.sendMessage(Util.java:23)
W/System.err( 9994): at
com.kskkbys.unitygcmplugin.UnityGCMIntentService.onMessage(UnityGCMIntentService.java:50)
W/System.err( 9994): at
com.google.android.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.java:223)
W/System.err( 9994): at
android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
W/System.err( 9994): at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 9994): at android.os.Looper.loop(Looper.java:153)
W/System.err( 9994): at android.os.HandlerThread.run(HandlerThread.java:60)

id run over all threads here try everything still not working what can i do?

thanks!

**Comment by LeshM** [comment]
The error says it can't find method / function 'UnitySendMessage' in com.unity3d.player.UnityPlayer.
Did you define the Unity activities in the AndroidManifest.xml?

It should look like this:

<activity android:name="com.unity3d.player.UnityPlayerProxyActivity" android:launchMode="singleTask" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <activity android:name="com.unity3d.player.UnityPlayerActivity" android:launchMode="singleTask" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
    </activity>
    <activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:launchMode="singleTask" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <meta-data android:name="android.app.lib_name" android:value="unity" />
      <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false" />
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>

**Comment by Rafaelkas** [comment]
<?xml version="1.0" encoding="UTF-8"?>

-<manifest android:versionName="1.0" android:versionCode="1" android:theme="@android:style/Theme.NoTitleBar" android:installLocation="preferExternal" package="com.unity3d.player" xmlns:android="http://schemas.android.com/apk/res/android">

<supports-screens android:anyDensity="true" android:xlargeScreens="true" android:largeScreens="true" android:normalScreens="true" android:smallScreens="true"/>


-<application android:name="com.soomla.SoomlaApp" android:debuggable="true" android:label="@string/app_name" android:icon="@drawable/app_icon">


-<activity android:name="com.unity3d.player.UnityPlayerProxyActivity" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:launchMode="singleTask">


-<intent-filter>

<action android:name="android.intent.action.MAIN"/>

<category android:name="android.intent.category.LAUNCHER"/>

</intent-filter>

</activity>

<activity android:name="com.unity3d.player.UnityPlayerActivity" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:launchMode="singleTask"> </activity>


-<activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:launchMode="singleTask">

<meta-data android:name="android.app.lib_name" android:value="unity"/>

<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="false"/>

<meta-data android:name="unityplayer.UnityActivity" android:value="true"/>

</activity>

<meta-data android:name="AppsFlyerDevKey" android:value=""/>

<meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true"/>

<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>

<activity android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" android:name="com.facebook.unity.FBUnityLoginActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen"> </activity>

<activity android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" android:name="com.facebook.LoginActivity" android:configChanges="keyboardHidden|orientation"> </activity>

<activity android:name="com.facebook.unity.FBUnityDeepLinkingActivity" android:exported="true"> </activity>

<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ "/>

<activity android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" android:name="com.soomla.store.billing.google.GooglePlayIabService$IabActivity"/>

<meta-data android:name="billing.service" android:value="google.GooglePlayIabService"/>

<activity android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" android:name="com.facebook.unity.FBUnityDialogsActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen"> </activity>


-<receiver android:name="com.kskkbys.unitygcmplugin.UnityGCMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">


-<intent-filter>

<action android:name="com.google.android.c2dm.intent.RECEIVE"/>

<action android:name="com.google.android.c2dm.intent.REGISTRATION"/>

<category android:name="com.slotoparty.slotoparty"/>

</intent-filter>

</receiver>

<service android:name="com.kskkbys.unitygcmplugin.UnityGCMIntentService"/>




</application>

<uses-feature android:glEsVersion="0x00020000"/>

<uses-permission android:name="android.permission.INTERNET"/>

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

<uses-permission android:name="android.permission.WAKE_LOCK"/>

<uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>

<uses-permission android:name="com.android.vending.BILLING"/>







<permission android:name="com.slotoparty.slotoparty.permission.C2D_MESSAGE" android:protectionLevel="signature"/>

<uses-permission android:name="com.slotoparty.slotoparty.permission.C2D_MESSAGE"/>

<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>

<uses-permission android:name="android.permission.GET_ACCOUNTS"/>




</manifest>

here my mainfest...

**Comment by Rafaelkas** [comment]
i dont see in AndroidManifest.xml this - com.unity3d.player.UnityPlayer???

**Comment by Rafaelkas** [comment]
now i have this in the logs:
No implementation found for native
Lcom/unity3d/player/UnityPlayer;.UnitySendMessage:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)

**Comment by YashpalJavia** [comment]
hello
@Rafaelkas 
@LeshM 

I have same problem.


V/GCMBroadcastReceiver(2317): onReceive: com.google.android.c2dm.intent.RECEIVE

V/GCMRegistrar(2317): Setting the name of retry receiver class to com.kskkbys.unitygcmplugin.UnityGCMBroadcastReceiver

V/UnityGCMBroadcastReceiver(2317): getGCMIntentServcieClassName

V/GCMBroadcastReceiver(2317): GCM IntentService class: com.kskkbys.unitygcmplugin.UnityGCMIntentService

V/GCMBaseIntentService(2317): Acquiring wakelock
V/GCMBaseIntentService(2317): Intent service name: GCMIntentService-DynamicSenderIds-1

V/UnityGCMIntentService(2317): onMessage

V/UnityGCMIntentService(2317): from: 1094430958891

V/UnityGCMIntentService(2317): team: GPS_IM_OFF_Y

V/UnityGCMIntentService(2317): message: GPS_IM_OFF

V/UnityGCMIntentService(2317): collapse_key: do_not_collapse

D/dalvikvm(2317): Trying to load lib /data/app-lib/com.elluminati.mazerun-1/libmain.so 0x41ed9e38

D/dalvikvm(2317): Added shared lib /data/app-lib/com.elluminati.mazerun-1/libmain.so 0x41ed9e38

W/dalvikvm(2317): No implementation found for native Lcom/unity3d/player/UnityPlayer;.UnitySendMessage:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

W/System.err(2317): java.lang.UnsatisfiedLinkError: Native method not found: com.unity3d.player.UnityPlayer.UnitySendMessage:(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V

W/System.err(2317): 	at com.unity3d.player.UnityPlayer.UnitySendMessage(Native Method)

W/System.err(2317): 	at com.kskkbys.unitygcmplugin.Util.sendMessage(Util.java:23)

W/System.err(2317): 	at com.kskkbys.unitygcmplugin.UnityGCMIntentService.onMessage(UnityGCMIntentService.java:50)

W/System.err(2317): 	at com.google.android.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.java:223)

W/System.err(2317): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)

W/System.err(2317): 	at android.os.Handler.dispatchMessage(Handler.java:102)

W/System.err(2317): 	at android.os.Looper.loop(Looper.java:136)

W/System.err(2317): 	at android.os.HandlerThread.run(HandlerThread.java:61)

V/GCMBaseIntentService(2317): Releasing wakelock
