### ISSUE TITLE
gcm

### ISSUE THREAD

**Issue by Bestlis** [kobakei/unity-gcm#17]
Hello!
Before, I never worked with ruby.
I try to execute ruby script, but I get error:

c:\RubyFiles>ruby notif.rb
c:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': ca
nnot load such file -- gcm.jar (LoadError)
        from c:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in
`require'
        from notif.rb:1:in `<main>'

Where can I get file ruby?

**Comment by tkowalski** [comment]
Probably you solved problem but for others (I never worked with ruby too so did some research). It's missing ruby gem (package to handle Google Cloud Messaging -> gcm). You can install it by "sudo gem install gcm" (unix like OS, try to search it for windows). It worked for me (OSX).

**Comment by Bestlis** [comment]
Hello!

Thanks fo reply!
I wrote php client.

2015-03-26 11:23 GMT+02:00 tkowalski <notifications@github.com>:
